## Imports

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## DATA

In [5]:
diamonds = pd.read_csv("https://raw.githubusercontent.com/adijams01/SDC_Projects/main/Internship/project_2/diamonds.csv")
diamonds.head()

   Unnamed: 0  carat        cut  cut_ord color clarity  clarity_ord  price
0           1   0.51    Premium        4     F     VS1            4   1749
1           2   2.25       Fair        1     G      I1            1   7069
2           3   0.70  Very Good        3     E     VS2            5   2757
3           4   0.47       Good        2     F     VS1            4   1243
4           5   0.30      Ideal        5     G    VVS1            7    789

In [6]:
len(diamonds)

50000

## Preprocessing

In [7]:
# one hot encoding...
diamonds_one_hot = pd.get_dummies(diamonds)
diamonds_one_hot.head()

,Unnamed: 0,carat,cut_ord,clarity_ord,price,cut_Fair,cut_Good,cut_Ideal,cut_Premium,cut_Very Good,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,1,0.51,4,4,1749,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
1,2,2.25,1,1,7069,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,3,0.70,3,5,2757,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
3,4,0.47,2,4,1243,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,5,0.30,5,7,789,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0

In [8]:
X = diamonds_one_hot.drop("price", axis = 1)
y = diamonds_one_hot["price"]

In [9]:
X.head()

,Unnamed: 0,carat,cut_ord,clarity_ord,cut_Fair,cut_Good,cut_Ideal,cut_Premium,cut_Very Good,color_D,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,1,0.51,4,4,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
1,2,2.25,1,1,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,3,0.70,3,5,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
3,4,0.47,2,4,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,5,0.30,5,7,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [10]:
y.head()

0    1749
1    7069
2    2757
3    1243
4     789
Name: price, dtype: int64

In [11]:
# Data splitting 80:20
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,
                                                       y,
                                                       test_size=0.2,
                                                       random_state=42)

In [12]:
len(X) , len(X_train) , len(X_test), len(y) , len(y_train) , len(y_test)

(50000, 40000, 10000, 50000, 40000, 10000)

## Model_1

In [16]:
tf.random.set_seed(42)

# Add an extra layer and increase number of units
model_01 = tf.keras.Sequential([
  tf.keras.layers.Dense(10000),
  tf.keras.layers.Dense(1000),
  tf.keras.layers.Dense(100),
  tf.keras.layers.Dense(10),
  tf.keras.layers.Dense(1)
])

# Compile the model
model_01.compile(loss=tf.keras.losses.mae,
                          optimizer=tf.keras.optimizers.Adam(lr = 0.001),
                          metrics=['mae'])

history = model_01.fit(X_train, y_train, epochs=50)

WARNING:absl:`lr` is deprecated in Keras optimizer, please use `learning_rate` or use the legacy optimizer, e.g.,tf.keras.optimizers.legacy.Adam.

Epoch 1/50
1250/1250 [==============================] - 7s 5ms/step - loss: 3408.4412 - mae: 3408.4412
Epoch 2/50
1250/1250 [==============================] - 5s 4ms/step - loss: 2998.5923 - mae: 2998.5923
Epoch 3/50
1250/1250 [==============================] - 6s 5ms/step - loss: 2861.3088 - mae: 2861.3088
Epoch 4/50
1250/1250 [==============================] - 5s 4ms/step - loss: 2633.4614 - mae: 2633.4614
Epoch 5/50
1250/1250 [==============================] - 6s 4ms/step - loss: 2507.0754 - mae: 2507.0754
Epoch 6/50
1250/1250 [==============================] - 5s 4ms/step - loss: 2388.3677 - mae: 2388.3677
Epoch 7/50
1250/1250 [==============================] - 5s 4ms/step - loss: 2269.9316 - mae: 2269.9316
Epoch 8/50
1250/1250 [==============================] - 6s 5ms/step - loss: 2158.3562 - mae: 2158.3562
Epoch 9/50
1250/1250 [==============================] - 5s 4ms/step - loss: 2109.8262 - mae: 2109.8262
Epoch 10/50
1250/1250 [==============================] - 7s 5ms/step - loss: 2001.0546 - mae: 2001.0546
Epoch 11/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1880.7960 - mae: 1880.7960
Epoch 12/50
1250/1250 [==============================] - 6s 5ms/step - loss: 1829.6729 - mae: 1829.6729
Epoch 13/50
1250/1250 [==============================] - 6s 5ms/step - loss: 1766.7896 - mae: 1766.7896
Epoch 14/50
1250/1250 [==============================] - 6s 5ms/step - loss: 1678.4572 - mae: 1678.4572
Epoch 15/50
1250/1250 [==============================] - 6s 5ms/step - loss: 1711.1003 - mae: 1711.1003
Epoch 16/50
1250/1250 [==============================] - 6s 5ms/step - loss: 1627.2054 - mae: 1627.2054
Epoch 17/50
1250/1250 [==============================] - 6s 5ms/step - loss: 1646.9006 - mae: 1646.9006
Epoch 18/50
1250/1250 [==============================] - 6s 5ms/step - loss: 1624.0883 - mae: 1624.0883
Epoch 19/50
1250/1250 [==============================] - 6s 5ms/step - loss: 1549.7209 - mae: 1549.7209
Epoch 20/50
1250/1250 [==============================] - 7s 6ms/step - loss: 1540.6006 - mae: 1540.6006
Epoch 21/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1411.2351 - mae: 1411.2351
Epoch 22/50
1250/1250 [==============================] - 6s 4ms/step - loss: 1430.2151 - mae: 1430.2151
Epoch 23/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1378.1534 - mae: 1378.1534
Epoch 24/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1415.4557 - mae: 1415.4557
Epoch 25/50
1250/1250 [==============================] - 6s 4ms/step - loss: 1379.3610 - mae: 1379.3610
Epoch 26/50
1250/1250 [==============================] - 6s 4ms/step - loss: 1407.1594 - mae: 1407.1594
Epoch 27/50
1250/1250 [==============================] - 6s 4ms/step - loss: 1323.4902 - mae: 1323.4902
Epoch 28/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1210.4261 - mae: 1210.4261
Epoch 29/50
1250/1250 [==============================] - 6s 4ms/step - loss: 1240.0227 - mae: 1240.0227
Epoch 30/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1225.7622 - mae: 1225.7622
Epoch 31/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1184.4641 - mae: 1184.4641
Epoch 32/50
1250/1250 [==============================] - 6s 5ms/step - loss: 1214.4336 - mae: 1214.4336
Epoch 33/50
1250/1250 [==============================] - 6s 5ms/step - loss: 1249.4164 - mae: 1249.4164
Epoch 34/50
1250/1250 [==============================] - 6s 5ms/step - loss: 1251.1320 - mae: 1251.1320
Epoch 35/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1203.4858 - mae: 1203.4858
Epoch 36/50
1250/1250 [==============================] - 6s 5ms/step - loss: 1209.1503 - mae: 1209.1503
Epoch 37/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1196.5050 - mae: 1196.5050
Epoch 38/50
1250/1250 [==============================] - 6s 4ms/step - loss: 1218.6313 - mae: 1218.6313
Epoch 39/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1174.6274 - mae: 1174.6274
Epoch 40/50
1250/1250 [==============================] - 6s 4ms/step - loss: 1132.5936 - mae: 1132.5936
Epoch 41/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1175.0048 - mae: 1175.0048
Epoch 42/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1118.9373 - mae: 1118.9373
Epoch 43/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1108.8726 - mae: 1108.8726
Epoch 44/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1162.1067 - mae: 1162.1067
Epoch 45/50
1250/1250 [==============================] - 6s 5ms/step - loss: 1125.5072 - mae: 1125.5072
Epoch 46/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1159.7460 - mae: 1159.7460
Epoch 47/50
1250/1250 [==============================] - 6s 4ms/step - loss: 1101.7634 - mae: 1101.7634
Epoch 48/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1101.0035 - mae: 1101.0035
Epoch 49/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1099.0844 - mae: 1099.0844
Epoch 50/50
1250/1250 [==============================] - 5s 4ms/step - loss: 1075.1028 - mae: 1075.1028

In [20]:
model_01.evaluate(X_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 2971.3784 - mae: 2971.3784

[2971.37841796875, 2971.37841796875]

## Model_2

In [18]:
tf.random.set_seed(42)

# Add an extra layer and increase number of units
model_02 = tf.keras.Sequential([
  tf.keras.layers.Dense(10000),
  tf.keras.layers.Dense(1000),
  tf.keras.layers.Dense(100),
  tf.keras.layers.Dense(10),
  tf.keras.layers.Dense(1)
])

# Compile the model
model_02.compile(loss=tf.keras.losses.mae,
                          optimizer=tf.keras.optimizers.Adam(lr = 0.001),
                          metrics=['mae'])

history = model_02.fit(X_train, y_train, epochs=100)

WARNING:absl:`lr` is deprecated in Keras optimizer, please use `learning_rate` or use the legacy optimizer, e.g.,tf.keras.optimizers.legacy.Adam.

Epoch 1/100
1250/1250 [==============================] - 8s 5ms/step - loss: 3587.1704 - mae: 3587.1704
Epoch 2/100
1250/1250 [==============================] - 7s 5ms/step - loss: 3000.7546 - mae: 3000.7546
Epoch 3/100
1250/1250 [==============================] - 6s 5ms/step - loss: 2890.5005 - mae: 2890.5005
Epoch 4/100
1250/1250 [==============================] - 5s 4ms/step - loss: 2688.6731 - mae: 2688.6731
Epoch 5/100
1250/1250 [==============================] - 5s 4ms/step - loss: 2522.3308 - mae: 2522.3308
Epoch 6/100
1250/1250 [==============================] - 5s 4ms/step - loss: 2381.1790 - mae: 2381.1790
Epoch 7/100
1250/1250 [==============================] - 5s 4ms/step - loss: 2308.6145 - mae: 2308.6145
Epoch 8/100
1250/1250 [==============================] - 6s 4ms/step - loss: 2164.4829 - mae: 2164.4829
Epoch 9/100
1250/1250 [==============================] - 5s 4ms/step - loss: 2083.5950 - mae: 2083.5950
Epoch 10/100
1250/1250 [==============================] - 6s 4ms/step - loss: 2032.2982 - mae: 2032.2982
Epoch 11/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1912.1350 - mae: 1912.1350
Epoch 12/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1826.6830 - mae: 1826.6830
Epoch 13/100
1250/1250 [==============================] - 6s 5ms/step - loss: 1841.9932 - mae: 1841.9932
Epoch 14/100
1250/1250 [==============================] - 6s 5ms/step - loss: 1763.7032 - mae: 1763.7032
Epoch 15/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1658.0446 - mae: 1658.0446
Epoch 16/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1591.1733 - mae: 1591.1733
Epoch 17/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1706.5032 - mae: 1706.5032
Epoch 18/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1534.3698 - mae: 1534.3698
Epoch 19/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1489.7190 - mae: 1489.7190
Epoch 20/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1527.9397 - mae: 1527.9397
Epoch 21/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1474.2968 - mae: 1474.2968
Epoch 22/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1431.1075 - mae: 1431.1075
Epoch 23/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1410.2164 - mae: 1410.2164
Epoch 24/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1369.0145 - mae: 1369.0145
Epoch 25/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1347.7515 - mae: 1347.7515
Epoch 26/100
1250/1250 [==============================] - 6s 5ms/step - loss: 1386.7886 - mae: 1386.7886
Epoch 27/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1249.8608 - mae: 1249.8608
Epoch 28/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1252.5959 - mae: 1252.5959
Epoch 29/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1222.9143 - mae: 1222.9143
Epoch 30/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1323.6993 - mae: 1323.6993
Epoch 31/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1306.3802 - mae: 1306.3802
Epoch 32/100
1250/1250 [==============================] - 6s 5ms/step - loss: 1272.9722 - mae: 1272.9722
Epoch 33/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1227.7744 - mae: 1227.7744
Epoch 34/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1240.8018 - mae: 1240.8018
Epoch 35/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1258.2476 - mae: 1258.2476
Epoch 36/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1153.6482 - mae: 1153.6482
Epoch 37/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1218.0060 - mae: 1218.0060
Epoch 38/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1195.3606 - mae: 1195.3606
Epoch 39/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1156.4702 - mae: 1156.4702
Epoch 40/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1153.9387 - mae: 1153.9387
Epoch 41/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1178.8301 - mae: 1178.8301
Epoch 42/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1093.6198 - mae: 1093.6198
Epoch 43/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1173.0109 - mae: 1173.0109
Epoch 44/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1184.1199 - mae: 1184.1199
Epoch 45/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1137.5110 - mae: 1137.5110
Epoch 46/100
1250/1250 [==============================] - 7s 6ms/step - loss: 1153.6147 - mae: 1153.6147
Epoch 47/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1106.6217 - mae: 1106.6217
Epoch 48/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1097.7576 - mae: 1097.7576
Epoch 49/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1087.0160 - mae: 1087.0160
Epoch 50/100
1250/1250 [==============================] - 6s 5ms/step - loss: 1094.8132 - mae: 1094.8132
Epoch 51/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1122.7336 - mae: 1122.7336
Epoch 52/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1094.4742 - mae: 1094.4742
Epoch 53/100
1250/1250 [==============================] - 6s 5ms/step - loss: 1125.3291 - mae: 1125.3291
Epoch 54/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1033.3315 - mae: 1033.3315
Epoch 55/100
1250/1250 [==============================] - 6s 5ms/step - loss: 1092.0967 - mae: 1092.0967
Epoch 56/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1107.0614 - mae: 1107.0614
Epoch 57/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1083.2301 - mae: 1083.2301
Epoch 58/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1049.6895 - mae: 1049.6895
Epoch 59/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1056.9086 - mae: 1056.9086
Epoch 60/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1081.3240 - mae: 1081.3240
Epoch 61/100
1250/1250 [==============================] - 5s 4ms/step - loss: 998.2234 - mae: 998.2234
Epoch 62/100
1250/1250 [==============================] - 6s 4ms/step - loss: 988.4560 - mae: 988.4560
Epoch 63/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1034.4218 - mae: 1034.4218
Epoch 64/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1023.9636 - mae: 1023.9636
Epoch 65/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1002.7727 - mae: 1002.7727
Epoch 66/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1043.0049 - mae: 1043.0049
Epoch 67/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1015.4075 - mae: 1015.4075
Epoch 68/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1035.5311 - mae: 1035.5311
Epoch 69/100
1250/1250 [==============================] - 6s 5ms/step - loss: 1008.2671 - mae: 1008.2671
Epoch 70/100
1250/1250 [==============================] - 5s 4ms/step - loss: 993.3611 - mae: 993.3611
Epoch 71/100
1250/1250 [==============================] - 6s 5ms/step - loss: 1090.5928 - mae: 1090.5928
Epoch 72/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1018.1937 - mae: 1018.1937
Epoch 73/100
1250/1250 [==============================] - 6s 4ms/step - loss: 988.9161 - mae: 988.9161
Epoch 74/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1033.2816 - mae: 1033.2816
Epoch 75/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1011.5823 - mae: 1011.5823
Epoch 76/100
1250/1250 [==============================] - 6s 4ms/step - loss: 998.5141 - mae: 998.5141
Epoch 77/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1000.4589 - mae: 1000.4589
Epoch 78/100
1250/1250 [==============================] - 6s 5ms/step - loss: 996.0213 - mae: 996.0213
Epoch 79/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1059.7318 - mae: 1059.7318
Epoch 80/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1020.7388 - mae: 1020.7388
Epoch 81/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1022.0044 - mae: 1022.0044
Epoch 82/100
1250/1250 [==============================] - 6s 5ms/step - loss: 997.5997 - mae: 997.5997
Epoch 83/100
1250/1250 [==============================] - 6s 5ms/step - loss: 989.8174 - mae: 989.8174
Epoch 84/100
1250/1250 [==============================] - 5s 4ms/step - loss: 950.2680 - mae: 950.2680
Epoch 85/100
1250/1250 [==============================] - 6s 5ms/step - loss: 992.6075 - mae: 992.6075
Epoch 86/100
1250/1250 [==============================] - 5s 4ms/step - loss: 1002.0185 - mae: 1002.0185
Epoch 87/100
1250/1250 [==============================] - 6s 4ms/step - loss: 1002.7354 - mae: 1002.7354
Epoch 88/100
1250/1250 [==============================] - 5s 4ms/step - loss: 945.9310 - mae: 945.9310
Epoch 89/100
1250/1250 [==============================] - 5s 4ms/step - loss: 961.5693 - mae: 961.5693
Epoch 90/100
1250/1250 [==============================] - 5s 4ms/step - loss: 993.6152 - mae: 993.6152
Epoch 91/100
1250/1250 [==============================] - 5s 4ms/step - loss: 976.7683 - mae: 976.7683
Epoch 92/100
1250/1250 [==============================] - 6s 4ms/step - loss: 955.6576 - mae: 955.6576
Epoch 93/100
1250/1250 [==============================] - 5s 4ms/step - loss: 963.1664 - mae: 963.1664
Epoch 94/100
1250/1250 [==============================] - 6s 4ms/step - loss: 971.1182 - mae: 971.1182
Epoch 95/100
1250/1250 [==============================] - 5s 4ms/step - loss: 974.3564 - mae: 974.3564
Epoch 96/100
1250/1250 [==============================] - 6s 4ms/step - loss: 963.2395 - mae: 963.2395
Epoch 97/100
1250/1250 [==============================] - 5s 4ms/step - loss: 962.6195 - mae: 962.6195
Epoch 98/100
1250/1250 [==============================] - 5s 4ms/step - loss: 956.7310 - mae: 956.7310
Epoch 99/100
1250/1250 [==============================] - 6s 4ms/step - loss: 972.2542 - mae: 972.2542
Epoch 100/100
1250/1250 [==============================] - 5s 4ms/step - loss: 990.5681 - mae: 990.5681

In [19]:
model_02.evaluate(X_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 729.4762 - mae: 729.4762

[729.4761962890625, 729.4761962890625]